# Generated by Django 4.2.11 on 2025-01-20 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('pub_date', models.DateField(auto_now=True)),
                ('due_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Task_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pub_date', models.DateField(auto_now=True)),
                ('tasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='to_do.task')),
            ],
        ),
    ]
