# Generated by Django 4.2.11 on 2025-01-20 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_list_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
