# Generated by Django 4.2.11 on 2025-01-20 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0002_task_task_list_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_list_id',
        ),
        migrations.AddField(
            model_name='task',
            name='done',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Task_list',
        ),
    ]
