# Generated by Django 4.2.11 on 2025-01-20 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0003_remove_task_task_list_id_task_done_delete_task_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
